name: data-validation
command: /data-validation
version: "1.0"
category: Phase2-MLOps
description: >
  Validate data quality, schema compliance, and detect anomalies.
  Generates validation report and can fail pipeline on critical issues.

triggers:
  - "Validate dataset schema"
  - "Check data quality"
  - "Generate data validation report"
  - "Validate <dataset>"

inputs:
  - name: dataset
    type: string
    required: true
    description: "Dataset path or name in data/processed/"
  - name: schema
    type: string
    required: false
    description: "Schema definition file (YAML). If omitted, infers from data"
  - name: strict
    type: boolean
    required: false
    default: false
    description: "If true, exit non-zero on any warning (CI gate mode)"
  - name: rules
    type: string
    required: false
    description: "Path to custom validation rules YAML"

outputs:
  - path: "reports/validation/validation_{dataset}_{date}.json"
    description: "Machine-readable validation results"
  - path: "reports/validation/validation_{dataset}_{date}.html"
    description: "Human-readable validation report"
  - path: "config/schemas/{dataset}_schema.yml"
    description: "Inferred or updated schema (if --schema not provided)"

dependencies:
  - pandas
  - pydantic
  - great-expectations  # optional, for rich rule engine
  - yaml

workflow:
  1. Load dataset
  2. Load or infer schema (types, nullable, ranges, cardinality)
  3. Schema compliance check: columns present, correct dtypes
  4. Nullability check: flag columns exceeding null threshold
  5. Range/value validation: numeric bounds, enum membership
  6. Duplicate row detection
  7. Outlier detection (IQR or Z-score)
  8. Referential integrity checks (if rules specify foreign keys)
  9. Summarize: PASS / WARN / FAIL per check
  10. Generate HTML + JSON reports
  11. If --strict and any FAIL/WARN: exit code 1
