name: report-builder
command: /report-builder
version: "1.0"
category: Phase3-Infrastructure
description: >
  Build ML experiment and model performance reports.
  Compiles metrics, generates visualizations, creates model cards and HTML/PDF summaries.

triggers:
  - "Generate model report"
  - "Create experiment summary"
  - "Build performance dashboard"
  - "Report for <model_name>"

inputs:
  - name: target
    type: string
    required: true
    description: "Report target: model:<name> | experiment:<id> | summary | dashboard"
  - name: format
    type: string
    required: false
    default: "html"
    description: "Output format: html | pdf | markdown"
  - name: period
    type: string
    required: false
    description: "Time period filter for summary reports (e.g. '7d', '30d', 'all')"

outputs:
  - path: "reports/{target}_{date}.html"
    description: "Full HTML report with inline plots"
  - path: "reports/{target}_{date}.pdf"
    description: "PDF version (if format=pdf)"
  - path: "artifacts/models/{name}/model_card.md"
    description: "Model card (if target=model)"

dependencies:
  - matplotlib
  - pandas
  - jinja2  # for HTML templating
  - weasyprint  # optional, for PDF export

workflow:
  1. Determine report type from target
  2. Load relevant data:
     - model: metrics, config, confusion matrix, ROC curve
     - experiment: all experiment logs for comparison
     - summary: aggregate stats across all experiments
  3. Generate visualizations:
     - Performance metrics bar chart
     - Confusion matrix heatmap (classification)
     - ROC/PR curves
     - Training curves (if available)
     - Feature importance plot
  4. Render report via Jinja2 template
  5. If format=pdf: convert with weasyprint
  6. If target=model: also generate/update model_card.md
  7. Save report + print location
