name: test-coverage
command: /test-coverage
version: "1.0"
category: Phase3-Infrastructure
description: >
  Analyze test coverage, generate reports, identify untested modules,
  and suggest test cases for low-coverage code.

triggers:
  - "Check test coverage"
  - "Generate coverage report"
  - "Identify untested code"
  - "Coverage check"

inputs:
  - name: module
    type: string
    required: false
    description: "Specific module to check. If omitted, scans entire src/"
  - name: threshold
    type: integer
    required: false
    default: 80
    description: "Minimum coverage % to pass. Below this triggers suggestions"
  - name: suggest
    type: boolean
    required: false
    default: true
    description: "If true, generate test case suggestions for gaps"

outputs:
  - path: "reports/coverage/coverage_{date}.html"
    description: "HTML coverage report (via pytest-cov)"
  - path: "reports/coverage/gaps_{date}.md"
    description: "List of untested code paths with suggested test cases"
  - path: ".claude/_RnD/coverage_history.csv"
    description: "Append-only coverage trend log"

dependencies:
  - pytest
  - pytest-cov
  - coverage

workflow:
  1. Run pytest --cov=src --cov-report=html --cov-report=json
  2. Parse coverage.json for per-module stats
  3. Identify modules below threshold
  4. For each low-coverage module:
     a. Read source code
     b. Identify untested branches/functions
     c. Suggest test scenarios
  5. Generate gaps report (Markdown)
  6. Append to coverage history log
  7. Print summary: overall %, top gaps, suggestions
  8. Exit non-zero if overall coverage < threshold (CI-safe)
