name: integration-test
command: /integration-test
version: "1.0"
category: Phase3-Infrastructure
description: >
  Generate and run integration tests for pipelines and APIs.
  Creates fixtures, mocks external deps, and validates end-to-end flows.

triggers:
  - "Create integration tests"
  - "Test end-to-end pipeline"
  - "Validate API integration"
  - "Integration test for <component>"

inputs:
  - name: target
    type: string
    required: true
    description: "Component to test: pipeline name, API endpoint, or 'all'"
  - name: generate_only
    type: boolean
    required: false
    default: false
    description: "If true, generate test code without running"
  - name: fixtures_dir
    type: string
    required: false
    default: "tests/fixtures"
    description: "Directory for test fixture data"

outputs:
  - path: "tests/integration/test_{target}.py"
    description: "Generated integration test module"
  - path: "tests/fixtures/{target}/"
    description: "Test fixtures (sample data, mocked responses)"
  - path: "reports/integration/results_{target}_{date}.json"
    description: "Test results (pass/fail with details)"

dependencies:
  - pytest
  - pytest-mock
  - httpx  # for API testing
  - dagster  # for pipeline testing

workflow:
  1. Analyze target component (pipeline assets or API routes)
  2. Identify external dependencies (DB, APIs, files)
  3. Generate fixtures: sample input data, mocked responses
  4. Generate test module:
     - Setup/teardown with fixture injection
     - Happy path: full flow with expected outputs
     - Error paths: missing data, bad input, timeout
     - Edge cases: empty datasets, large payloads
  5. If NOT generate_only: run tests with pytest -v
  6. Save results JSON
  7. Print summary table
