name: data-profiler
command: /data-profiler
version: "1.0"
category: Phase3-Infrastructure
description: >
  Generate comprehensive data profiles and catalog entries.
  Documents data lineage, schema, and statistical properties.

triggers:
  - "Profile dataset"
  - "Generate data catalog entry"
  - "Analyze data distribution"
  - "Profile <dataset>"

inputs:
  - name: dataset
    type: string
    required: true
    description: "Dataset file or name in data/"
  - name: catalog_update
    type: boolean
    required: false
    default: true
    description: "If true, update the project data catalog"
  - name: lineage
    type: boolean
    required: false
    default: false
    description: "If true, trace and document data lineage"

outputs:
  - path: "reports/profiles/profile_{dataset}_{date}.html"
    description: "Rich interactive HTML profile report"
  - path: "docs/data-catalog/{dataset}.md"
    description: "Data catalog entry in Markdown"
  - path: "docs/data-catalog/catalog_index.yml"
    description: "Updated catalog index"

dependencies:
  - pandas
  - ydata-profiling  # for rich profiling reports
  - pyyaml

workflow:
  1. Load dataset
  2. Run ydata-profiling (or pandas-profiling) for full report
  3. Extract key stats: shape, dtypes, nulls, unique counts, top values
  4. Detect data types: numeric, categorical, datetime, text, id
  5. If --lineage: trace source files/transforms in pipeline code
  6. Generate catalog entry (Markdown) with:
     - Description, owner, schema table, sample rows
     - Update frequency, source system, lineage graph
  7. Update catalog_index.yml
  8. Save HTML profile + catalog entry
