name: feature-engineer
command: /feature-engineer
version: "1.0"
category: Phase1-CoreML
description: >
  Feature engineering assistant: analyze existing features, suggest and generate
  new features (polynomial, interaction, time-based), test importance, and output
  production-ready feature pipeline code.

triggers:
  - "Create polynomial features"
  - "Test feature interactions"
  - "Generate time-based features"
  - "Engineer features for <dataset>"
  - "Suggest features"

inputs:
  - name: dataset
    type: string
    required: true
    description: "Dataset in data/processed/"
  - name: target
    type: string
    required: true
    description: "Target column for importance ranking"
  - name: strategy
    type: string
    required: false
    default: "auto"
    description: "Feature strategy: auto | polynomial | interaction | time_based | all"

outputs:
  - path: "src/features/feature_defs_{dataset}.yml"
    description: "Feature definitions YAML (reusable across pipelines)"
  - path: "src/features/engineer_{dataset}.py"
    description: "Generated feature engineering script"
  - path: "reports/features/importance_{dataset}_{date}.html"
    description: "Feature importance report with plots"

dependencies:
  - pandas
  - numpy
  - scikit-learn
  - matplotlib

workflow:
  1. Load dataset and profile existing features
  2. Detect column types (numeric, categorical, datetime)
  3. Based on strategy, generate candidate features:
     - polynomial: x^2, x^3 for top numeric features
     - interaction: pairwise products of top features
     - time_based: day_of_week, hour, month, is_weekend (if datetime cols present)
     - auto: detect column types and apply appropriate strategies
  4. Train a quick RandomForest to rank all features (original + new) by importance
  5. Filter: keep features with importance above threshold
  6. Output feature definitions YAML + generated Python code
  7. Save importance report
